scraping/thumbnails/Makefile
scraping/thumbnails/README.md

Added firefox dependency

---

scraping/thumbnails/Makefile
scraping/thumbnails/README.md
scraping/thumbnails/invasives.csv
scraping/thumbnails/natives.csv
scraping/thumbnails/scrape.py
scraping/thumbnails/scrape_fish.py

As per @thenomemac suggestion, thumbnails are good enough.
This works much, much better for the whole scraping process as it gets urls and downloads the images in one fell swoop.
If you want to do specific fish you can edit all_fish.csv with just the fish you want.
(so far I've downloaded carp and walleye pictures)

Add thumbnail scraper

---

fishr/README.md

update to readme #14

---

fishr/README.md
fishr/run.sh

Add run.sh for launching fishr app

---

fishr/run.sh

Fix run.sh to point to correct flask file

---

modeling/train_head.py

A few enhancements from this afternoon

Add extra layers to model and full model scoring at end

---

.gitignore

Update gitignore to ignore crap

---

fishr/static/style.css
fishr/templates/base.html
fishr/templates/regulations.html

Some styling updates for tables.  Not a ton better, but a little bit more readable.

Update table formatting

---

modeling/arrs_to_emb.py
modeling/train_head.py

This is the last training unit in the resnet model.
Also, callbacks and ability to re-train from previous best model were added.
This looks like a promising way forward, using our existing data and *not* adding any hidden dense layers I was able to get to:
484s - loss: 0.0083 - categorical_accuracy: 0.9983 - val_loss: 0.8114 - val_categorical_accuracy: 0.8740
So I think we can tweak this a bit if need be but really we should do the "get moar data!" suggestion. 
This is after slowing down the learning rate twice by a factor of 4 (for some reason I swear thats what you suggested to me josiah, but I could be making that up) and picking up from the previous run's best checkpoint.
Oh and the model is slow to train now :(  but if you are patient and doing family stuff it isn't too bad :)

Train resnet model on last 12 layers.

---

fishr/fishr.py
fishr/models.py
fishr/templates/label.html
fishr/templates/submission_results.html

working labeling interface for app that caches to db

working label webpage that caches to db

---

fishr/fishr.py
fishr/score_fish_pic.py

Example dict for you to interface with @matthew-sochor, will be returned from ".get(fish_pic_id)" on database:
```
{'img_path': '/home/thenome/fish.io.ai/data/fish_pics/18d44905-06fb-4b85-811a-d3f2367821fe.jpg', 'species_pred': 'carp', 'y_labs': ['carp', 'walleye', 'white_perch', 'yellow_perch'], 'y_pred': [0.9997746348381042, 7.380048919003457e-05, 0.000131766137201339, 1.973541293409653e-05], 'results': {'species': 'carp', 'invasive': True, 'length': 8}}
```

Scores array to db

---

fishr/templates/label.html

fix text color in label html

---

fishr/fishr.py
fishr/templates/download_cache.html
fishr/templates/index.html
fishr/templates/submission_results.html

what's running in prod for our second vid demo

Redeploy for vid2

---

fishr/fishr.py
fishr/templates/about.html
fishr/templates/base.html
fishr/templates/index.html
modeling/install.sh

aws deep learning install script

aws install script

---

fishr/fishr.py
fishr/templates/base.html
fishr/templates/legal.html

added legal TOS. Didn't spend much time on it cause I'm not a lawyer or even expert at all. So wording is poor but says we claim nothing in this app use at your own risk and email us for DMCA. Should cover our butts for now. issue #62
also added navbar menu to find all these pages. It's formatting is still off a bit but we'll revisit the whole CSS file again before final demo, ex:

Legal pages

---

fishr/fishr.py
fishr/templates/base.html
fishr/templates/legal.html

Only last commit matters branched from #66 
wanted to get some tracking on site asap to inform us if anyone is going to site yet can add whatismyfish@gmail.com tracking in pull later this week

Google analytics

---

fishr-cli.sh
fishr/fishr.py
fishr/templates/base.html
fishr/templates/label.html
fishr/templates/legal.html
fishr/templates/submission_results.html

working thumbnail features complete with pages loading smaller thumbnails from cdn route and cacheing all images large/small sizes in jpg compression

Cache thumbnail

---

.gitignore
modeling/Makefile
modeling/README.md
modeling/main.tf

Start, ssh into and stop a GPU on AWS through makefile and terraform magics

Deploy gpu

---

modeling/.env
modeling/Makefile
modeling/README.md
modeling/main.tf
modeling/train_head.py
modeling/variables.tf

Lets make this more reproducible, yo

Makefile for modeling

---

fishr/fishr.py

Extract lat and lon from uploaded image meta data, if possible.

---

modeling/Makefile
modeling/README.md
modeling/arrs_to_aug.py
modeling/predict.py

89% accuracy weights on S3 generated with this code:
s3://what-is-my-fish-images/models/resnet-4-24-2017-fish-17-acc-89.hdf5

Resnet on 17 fish

---

fishr/nginx/fishr.conf

added your config file to a pull

cert file added to nginx config
